### ISSUE TITLE
bb views part 2

### ISSUE THREAD

**Issue by jshawl** [ga-dc/curriculum#260]
lesson - https://github.com/ga-dc/pbj/blob/1dc46e7620fab380b37f0383dad1e12459de869a/10-back-and-front-of-front-end/bb_views_part2/readme.md
trello - https://trello.com/c/NJQp3VKf/43-bb-views-part-2

**Comment by mattscilipoti** [comment]
Δ: Start with the big picture.  Show that we will be replacing the list code from this morning.  Maybe make placeholders for the methods - showing the call flow (via console.logs?), then fill in the code.  We are creating `#renderOne`, but we don't know why.

**Comment by mattscilipoti** [comment]
Δ: Simple, clear example of how `this.collection.each` works.  In CodePen or similar?

**Comment by mattscilipoti** [comment]
Δ: Can we utilize `renderAll` in app.js before events?  Then, show the need for responding to events by changing something on the page and see that it isn't updating.

**Comment by mattscilipoti** [comment]
➕: Nice separation of collection views and "specialty" views.
➕: process raised good questions from students.  Kept them engaged.

**Comment by mattscilipoti** [comment]
Δ: Student asked to provide references to other Backbone applications that they could read through.
