### ISSUE TITLE
bootstrap n' foundation

### ISSUE THREAD

**Issue by jshawl** [ga-dc/curriculum#261]
lesson - https://github.com/ga-dc/pbj/blob/1dc46e7620fab380b37f0383dad1e12459de869a/10-back-and-front-of-front-end/bootstrap/readme.md
trello - https://trello.com/c/IGcgfat8/44-bootstrap

**Comment by RobertAKARobin** [comment]
Aw, yiss. Was just going to ask if you could do this.

**Comment by jshawl** [comment]
∆: Include more student demos. Would be nice to see student examples of in-class work
+: including customization w/ sass was smart. I have lost so much time fighting bootstrap selectors. 
+: including bootstrap *and* foundation was a great idea. Felt like the pace was right on track, gives students familiarity with two frameworks
+: also really enjoyed part on design. To give yourself more cred while teaching, consider having links handy that backup what you're saying. e.g. some color palette tools or type pairing sites like http://hellohappy.org/beautiful-web-type/ or http://justmytype.co/

**Comment by RobertAKARobin** [comment]
Thanks!
