### ISSUE TITLE
Github Issue

### ISSUE THREAD

**Issue by jnichols300** [ga-dc/curriculum#289]
https://github.com/jnichols300?tab=repositories

https://github.com/jnichols300/resumehtml

https://github.com/jnichols300/applepies

If I did this right I feel great about it 5, 5. If not....well maybe 3-4, 3-4 for comfort and completeness!

**Comment by jnichols300** [comment]
oops it should be jnichols300/jnichols300.github.io

**Comment by jnichols300** [comment]
it should also be this for the curriculum https://github.com/jnichols300/curriculum

**Comment by andrewsunglaekim** [comment]
:+1:  Looks totally fine
