### ISSUE TITLE
Cassidy Git homework

### ISSUE THREAD

**Issue by Cajam** [ga-dc/curriculum#302]
https://github.com/Cajam/cajam.github.io

http://cajam.github.io/cajam/

https://github.com/ga-dc/curriculum

Comfort Level: 4

Completeness: 5

**Comment by jshawl** [comment]
:+1: Please fork the curriculum repo - https://github.com/ga-dc/curriculum to your account

**Comment by Cajam** [comment]
Done. Thanks, Jesse!
