### ISSUE TITLE
Ly - Fork and Clone Curriculum Repo

### ISSUE THREAD

**Issue by Ly900** [ga-dc/curriculum#305]
comfort_level: 3
completeness: 5

Link to your personal Github pages repo:
https://github.com/Ly900/Ly900.github.io

Link to the URL to see your hosted page:
Ly900.github.io/ly_nguyen_resume.html

Link to the repo you forked:
https://github.com/Ly900/curriculum

**Comment by andrewsunglaekim** [comment]
:+1:
