### ISSUE TITLE
Day 2 HW

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/curriculum#310]
comfort: 5
completeness: 5

I got a 404 error when trying to access my "dan-ator.github.io" and I am not sure why.

Personal Github pages repo: https://github.com/dan-ator?tab=repositories
forked repo: https://github.com/dan-ator/curriculum
dan-ator.github.io

**Comment by timothytgregg** [comment]
try renaming your resume txt file to 'index.html' 

(:

**Comment by dan-ator** [comment]
Thanks! It works now. Nice.
