### ISSUE TITLE
Tomework Who?

### ISSUE THREAD

**Issue by timothytgregg** [ga-dc/curriculum#311]
my repo page: https://github.com/timothytgregg?tab=repositories

my webpage: http://timothytgregg.github.io/

my forqued curriculum page: https://github.com/timothytgregg/curriculum

comfort_level: 5
completeness: 5

**Comment by jshawl** [comment]
https://github.com/timothytgregg/curriculum seems to be some other curriculum. Either rename this one or the ga-dc one to forque.

:+1:

**Comment by timothytgregg** [comment]
oh, weird! 

here's the GA forked curriculum instead: 

https://github.com/timothytgregg/curriculum-1
