### ISSUE TITLE
#javascript-data-types-conditionals-loops

### ISSUE THREAD

**Issue by ebirving** [ga-dc/curriculum#334]
+ Great examples! Both the planned ones and the live-coded ones.
&Delta; The second half could have used a you do -- there are a couple in the lesson plan, but they didn't happen...

**Comment by andrewsunglaekim** [comment]
Yeah, unfortunately, i think this is a timing issue. It's alot of content because it used to be 2 lessons. Alot of the exercises were cut..maybe find a place in the lesson to use a you dofor them to learn.
