### ISSUE TITLE
HTML Resume Part 2 + Clone Curriculum

### ISSUE THREAD

**Issue by jordanbrauner** [ga-dc/curriculum#337]
comfort_level: 4
completeness: 5

Personal GitHub pages repo: https://github.com/jordanbrauner?tab=repositories
URL of my hosted page: http://jordanbrauner.github.io/
Link to the forked curriculum repo: https://github.com/jordanbrauner/curriculum

URL of my hosted resume: https://github.com/jordanbrauner

**Comment by amaseda** [comment]
:+1:
