### ISSUE TITLE
Single Page Web Apps: New Google crawling procedure

### ISSUE THREAD

**Issue by mattficke** [ga-dc/curriculum#349]
The section on the downsides of SPAs may need updating now that Google has a new crawling scheme for AJAX-reliant pages: http://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html

Their bot now indexes the JS and CSS files along with the HTML to better capture how pages actually appear to users. Should minimize SEO issues.

(I sort of feel like I'm communicating from beyond the grave here. Hope the new class is going well!)

**Comment by jshawl** [comment]
:+1: SOO HAPPY TO SEE AN ISSUE FROM YOU :)

**Comment by RobertAKARobin** [comment]
:tada:
