### ISSUE TITLE
jQuery 1 (Adam)

### ISSUE THREAD

**Issue by ebirving** [ga-dc/curriculum#374]
&Delta; It might be good to add a code snippet or two demonstrating how/where to include your script tags in the html. A number of people seemed to miss that somehow...

&Delta; The $(document).ready() section needs a "why"

&Delta; Use the words get/getter and set/setter in the examples under `.html()`, `.attr()`, and `.css()`? ?&mdash; i.e. "With an HTML attribute as an arguments, returns ("gets")..."

&Delta; / \+ Add "do'ers" concept to notes? ALSO, that table you made was super helpful. I saw a couple of people whip out their phones and take a pic

&Delta; / \+ I might pull the bullet point about `.eq()`up a level, rather than having it be a sub-bullet to the line beginning "jQuery runs...".  A line explicitly addressing the difference between this and the [] equivalent in Vanilla JS would also be great here. The compare/contrast strategy is a really strong thread in this lesson, and tying it in here could help cement this understanding.

&Delta; / \+ I think it makes sense to move $(document).ready() below Some jQuery Methods, as you actually delivered it. This sequence made sense.

\+ Spotlight on the difference between behavior of jQuery objects, DOM elements, and arrays was awesome

\+ LOVE THAT GIF

**Comment by adambray** [comment]
@ebirving 
:trophy: 

This is the BEST feedback I've ever received during a single lesson.... thanks so much! Working on capturing it into the lesson plan this week!
