### ISSUE TITLE
ruby-enumerables(Adrian)

### ISSUE THREAD

**Issue by nolds9** [ga-dc/curriculum#397]
* + - Nice job cold calling, getting the students involved early
* ∆ - Make sure text isn't too small
* + - Really liked the loops activity. +1 for letting students share snippets.
* ∆ - `next` could use a new snippet
* + - Ruby enumerables group activity was great, there were some great teachbacks

**Comment by amaseda** [comment]
@nolds9 Thanks for these d00d!
