### ISSUE TITLE
Sinatra Rest 2(Robin)

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/curriculum#420]
`∆` - i'm not a fan of rendering in a post request. IE. when you used `@posted` to differentiate between `get "/"` vs `post "/"`

`∆` there something to be said about moving in sequence with the lesson plan. Moving around pieces of the lesson plan should be planned out more thoroughly prior to delivery. Additionally I'm not sure the value of the entirety of all the form stuff, might be conflaty? I like the example of forms in sinatra in the views portion of the lesson. 

Like the stuff in this header https://github.com/ga-dc/curriculum/blob/master/04-ruby-mvc-sinatra/sinatra-rest/views.md#we-do-forms is alot of the same information in the REST portion for forms. Only simpler and less defined which might be better for this since its confusing to begin with.

`+` - I like the heavy you do, also the music is nice during you dos =D

`+` - You bring a great energy to the room, i can't put my finger on what that is, its not excitable but calm even.

`+` - I really like your metaphors, I need to bring more of that to the table to help drive some points home.

`+` - i really liked when there's back and forth conversation between primary and support instructors, like with REST conventions today. As in, I brought up a point, and you typed out what "wrong" looks like it becomes clearer to the students. Maybe we can figure out better ways to pepper those in to drive home some points.

**Comment by RobertAKARobin** [comment]
The music is The Avalanches!

I liked the conversations too!
