### ISSUE TITLE
Sinatra Rest (Andy)

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#424]
* **+** Loved your use of questioning and asking for an improved answer the second time (using specific terms)
* **∆** Try to keep complexity to a minimum (e.g.: I wouldn't even bother mentioning custom layouts when introducing standard layouts)
* **∆** Be mindful of correct terminology (e.g. saying "if I had a 30 other websites in this", when we should really say "webpages"
* **∆** 'Names' example is a bit unclear due to the use of the word 'names' in different contexts: erb file, route, local, instance vars, and a redirect. Maybe differentiate those var names a bit.
* **∆** Use the whiteboard to write down lists of information, e.g. Data can appear in params from three places: url path, url query string, form data (with examples next to each)

**Comment by andrewsunglaekim** [comment]
Great points all, thanks as usual. Especially whiteboarding, I feel like thats the tool i'm the worst at using.
