### ISSUE TITLE
Sinatra REST (Robin)

### ISSUE THREAD

**Issue by ebirving** [ga-dc/curriculum#425]
&Delta; All three parts of this lesson would benefit from some sort of relational framing, ideally with a diagram(s) showing where each of the frameworks, DSLs, and concepts included in this marathon of new info fits into the "How the Web Works" paradigm we've been building on since day one. In fact, I would love to see one "roadmap" showing how and where all of the new technologies we're introducing this week fit together, shared among and referred to in all of the lesson plans. I think that would help mitigate some of the confusion (and anxiety) around the different order in which each class receives these lessons. I'd be down to pair on this with someone!

&Delta; I know this one we're all guilty of, but try to make sure you know which classes they've already had...

&plus; Lots of little things you did to encourage camaraderie/community/communication in the classroom today! Being explicit about welcoming feedback on the volume of the music, repeatedly encouraging people to work together, and building in lots of time for Q & A, plus your general approachable demeanor! This is a strength&mdash;build on it! Your mandatory stand up and walk around break demonstrates this. I think "Robin told me to pair with this specific new person" would be well received...

**Comment by RobertAKARobin** [comment]
Thank you!

**Comment by RobertAKARobin** [comment]
I've been really looking forward to Feedback From Erica™ but didn't want to put on the pressure. :)

**Comment by ebirving** [comment]
I hope the FFE&trade; experience lived up to expectations. :wink: Feedback on the feedback is always welcome!
