### ISSUE TITLE
rspec-walkthrough (Robin)

### ISSUE THREAD

**Issue by jmas13** [ga-dc/curriculum#430]
- (+) Framing with why do we use Sinatra reloader great

  - (+) Using landlord for first example test also very relevant -- let's students worry entirely about rspec already being familiar with the files

- (+) Slack driven lesson encourages collaboration which is really good. Student said "makes us think before typing code"

  - (+) I think this also allowed students to set the pace

  - (&Delta;) In the turn and talk "why TDD?" maybe frame with how did you like [oop_monkey](https://github.com/ga-dc/oop_monkey)

  - (+) Responses after the "why TDD?" turn and talk was excellent. I think this lesson really landed

- (+) Really glad you went over spec_helper and .rspec

**Comment by RobertAKARobin** [comment]
Thanks, John!
