### ISSUE TITLE
Views & Controllers (Robin)

### ISSUE THREAD

**Issue by ebirving** [ga-dc/curriculum#438]
&Delta; Not having the notes on the screen is great, but I would strongly and explicitly encourage people to keep the notes open for reference when you Slack them out. Partly as a security blanket, mostly to cut down on, "Wait--can you go back three steps?"

&Delta; One of the factors that may be contributing to the subdued mood in this cohort compared to the last is the weather/season. With that it mind, it would be good to create as many opportunities as possible for students to get up and move around. "Convert this T&T or ST-WG into a whiteboard-o-rama" may be a good strategy to keep at the front of the utility belt.

&Delta; Be careful about introducing the solution branch as an option when the starter code has proven buggy (mea culpa, mea culpa!)

&Delta; Reminder: fix the notation on the New Artist form. Need id's that match label for.

&plus; Consistently good job explaining why you're teaching in a certain way. Prime example: why you don't have the notes on the screen.

&plus; Way to call out the half-asleep student! On a similar note, :+1: for cold-calling with advance warning!

&plus; Love the redesigned rMVC diagram -- great way of introducing/reinforcing ERD-ish visual grammar in addition to the more metaphorical diagrams we use

&plus; Great job catching yourself and redirecting when answering a question instead of opening the floor for a student to answer.

**Comment by RobertAKARobin** [comment]
Yesss. Keep 'em coming.
