### ISSUE TITLE
Rails helpers (Adam)

### ISSUE THREAD

**Issue by jmas13** [ga-dc/curriculum#444]
- (+) I am now pro bunch of separate repos for all the different tunrs. I think it the class wouldn't have started so smoothly had students needed to find the right branch

- (&Delta;/+) Students seem to be confused with string interpolation.

- (+) This is a super question heavy class -- feel like you did a really good job balancing let's investigate and not worth diving into right now.

**Comment by jshawl** [comment]
from tuesday morn:

∆ - clone repo from class before to avoid "migration pending" error or having to `rake db:migrate:reset`
