### ISSUE TITLE
File location typo

### ISSUE THREAD

**Issue by starrchen** [ga-dc/curriculum#458]
`# app/views/playlists/show.html.erb` should be `/artists/show.html.erb`, right?

In Many-to-Many, under Updating controllers: https://github.com/ga-dc/curriculum/blob/master/05-mvc-with-rails/rails-many-to-many/README.md#updating-the-controller-15-minutes--205

**Comment by jshawl** [comment]
awesome catch! @starrchen want to fix this and submit a pull request?
