### ISSUE TITLE
Rails Deployment (Robin)

### ISSUE THREAD

**Issue by nolds9** [ga-dc/curriculum#463]
- +: Like how you framed this lesson, +1 for using a real world example of deployment, and how we now have the power to put things online!
- Δ:  Font was difficult to read in the back, make sure we zoom in and are clearing the console
- +:  "Can't find an artist with an id of: 8675309", +1 showing different errors in development, and production.

**Comment by ebirving** [comment]
&plus; Yeah, referencing industry experience! I see you, Coinbase :wink: 

&Delta; Your dry erase marker is a little faint and it's particularly difficult to read in the patch of reflected light/glare under/around the wifi password decal...
