### ISSUE TITLE
current_user doesn't save appointment

### ISSUE THREAD

**Issue by CBanks813** [ga-dc/curriculum#473]
So, I'm trying to save the users appointments that they have scheduled but I'm having trouble with the create controller. 
```
def create
    if current_user
      @service = Service.find(params[:service_id])
      @appointment = @service.appointments.create(appointment_params)

    end
    redirect_to services_path
  end
```

**Comment by RobertAKARobin** [comment]
Could you please post this on the Project 2 repo, Chrystal? https://github.com/ga-dc/project2/issues
