### ISSUE TITLE
API's(Nick)

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/curriculum#483]
`∆`- Felt a bit disjointed at times for flow. Not sure how to best fix this beyond practicing transitions a bit more.

`+` - really great job with timings however, stayed on track pretty well.

**Comment by jshawl** [comment]
∆ nice framing w/ apis! The focus was heavily on getting data from other people's databases. the DOM is also an api, but does not involve retrieving data. Maybe focus more on the word *interface*, or an api is a program that other programs can talk to...
