### ISSUE TITLE
Express 1 (Matt)

### ISSUE THREAD

**Issue by jshawl** [ga-dc/curriculum#485]

**Comment by jshawl** [comment]
+: Excellent framing at the beginning! really addressing the *why* for express and recalling big-picture concepts.

**Comment by jshawl** [comment]
+: nice intro to npm and package.json - recommend a flipped reading or you do early on to get students working on their own sooner

**Comment by mattscilipoti** [comment]
delta: it's one big We do.
delta: obvious hiccup as we transition into "Bodyparser & Post requests", cleaner example - inline with earlier examples.

**Comment by mattscilipoti** [comment]
delta: last exercise (Ultimate Compliment) needs work.  No link to [it](https://github.com/ga-dc/compliment-express), readme, solution.

**Comment by mattscilipoti** [comment]
delta: add info about express.static

**Comment by mattscilipoti** [comment]
delta: recommend another example.  Having difficulty fitting this into MVC model.  routes.js feels incorrect (the route is named in index.js).  controller.js?  Is the action "index"?  Answer isn't obvious.  I want the answer to be obvious, we just have to figure out how to codify it.

**Comment by jshawl** [comment]
thinking about addressing all these deltas in express 2 lesson:

- express.static
- mvc architecture and file naming conventions
- body parser and post requests
- handling json

**Comment by mattscilipoti** [comment]
delta: smaller steps during transition to views.  Use app.render.  See problem (no view template).  Create view w/o layout.  Show it.  Realize need for layout (via second view?).  Extract layout.  The current flow leaves us struggling to figure out why nothing is displayed - prior to learning about `{{{body}}}`.

**Comment by ebirving** [comment]
delta: Eep! How did wires get crossed on which lesson includes to "list everything we've learning so far"?
delta: Focus more on framing what `package.json` is before lingering on each line of the setup. Also, be careful about 
delta: I second the call for more on body-parser and post requests in express part II.

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
