### ISSUE TITLE
OOJS2 (Robin)

### ISSUE THREAD

**Issue by jshawl** [ga-dc/curriculum#520]
+: Love the immediate you-do. Going to try to implement this in my next lesson

**Comment by jshawl** [comment]
∆: this class hasn't had mongo yet - be sure to check sequence before delivering lesson plan

**Comment by jshawl** [comment]
instead of:

```js
var Artist = function(info){
  this.name = info.name;
  this.photoUrl = info.photoUrl;
  this.nationality = info.nationality;
  this.id = info.id;
};
```

you could do:

```js
var Artist = function(info){
  for(var k in info){
    this[k] = info[k];
  }
};
```

**Comment by RobertAKARobin** [comment]
Ooh, yeah. I like that much better. I just used this because I copied the front-end JS wholesale from the other Tunr repo.

**Comment by jshawl** [comment]
∆: easy way to reset to a branch: `git reset --hard <commit>` where commit is a branch, tag, or commit sha - https://git-scm.com/docs/git-reset
