### ISSUE TITLE
Git Teams (Erica)

### ISSUE THREAD

**Issue by adambray** [ga-dc/curriculum#522]
* **+** - Excellent introductory exercise (collecting commands) esp, the delivery
* **∆** - Would like to see more big picture framing during the intro (i.e. why are we doing this, maybe connecting to past / future lessons and exercises / projects)
* **+** - Excellent delivery of exercises, esp with responding to shortened time available.
* **∆** - The last question on rebasing was a tough one, and your answer (reviewing rebase as a concept was really good), but I think it's important to call out when you're going to take a detour in answering a question. i.e. "I'm going to get to the mechanics of how to rebase, and what `--continue` means, but first I want to quickly review what rebasing means"

**Comment by ebirving** [comment]
Thanks! These are really helpful!
