### ISSUE TITLE
TDD / Jasmine (Robin)

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/curriculum#537]
@andrewsunglaekim

**Comment by andrewsunglaekim** [comment]
`+` - as usual framing is excellent. You do a really great job breaking down concepts into understandable nuggets

`∆` would recommend to break up the you do prompts. Instead of list some stuff out individually then get into groups. Prompt them to list, then prompt the group activity after.

**Comment by jmas13** [comment]
- (+) Think this is a great project planning lesson. Best case scenario, students finish the lesson with tests they use in their projects and worst they've done solid planning and had the opportunity to talk to other groups.

- (+) Framing: do it like RSpec now here's how we implement it differently

- (&Delta;) I've noticed some students writing tests describing a users but are really writing feature tests. Things like "a user can search for locations" to describe a user I think should be "locations are searchable".
