### ISSUE TITLE
JS TDD (Erica)

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/curriculum#538]
Delivery:
- +: Good job using the break time to regroup (from speaker, recording, & other issues)

Lesson Plan:
- 𝞓: Spreadsheet may not be the best tool for realtime, collaborative creation of a list.  Started really rough, seems to have worked itself out.
- 𝞓: Show `tree` for directory structure (at start, as target,  and after building)
- 𝞓: `expect( olaf.name ).toEqual("Olaf");`  rather than toBeDefined.

**Comment by ebirving** [comment]
Thanks!
