### ISSUE TITLE
Git Q - Pull to My Machine

### ISSUE THREAD

**Issue by thomhouseholder** [ga-dc/curriculum#551]
I'm trying to pull a branch on my fork to my machine.  There are differences between what I see in the repo and what I have on my machine.

I tried git pull origin <branchname> and expected the local to update to match what's in my repo.

Instead, the message is  
* branch            thom-backend -> FETCH_HEAD
Already up-to-date.

**Comment by RobertAKARobin** [comment]
Wrong repo, Thom! Please submit it here instead: https://github.com/ga-dc/project3/issues
