### ISSUE TITLE
RWD (Matt)

### ISSUE THREAD

**Issue by jmas13** [ga-dc/curriculum#555]
- (+) framing in the class is excellent: http://screensiz.es, mediaqueri.es and xkcd

- (+) I like using jsfiddle or codepen. I think students will benefit with more practice with these

- (++) Lots of research in this class.

  - (+) Good practice for group dynamics

  - (+) Learning document diving techniques from one another

- (+) Good review at end

**Comment by ebirving** [comment]
&plus; Great, great framing! Would love to see more of directions/motivating questions for the screensizes and mediaqueries activities documented in the lesson plan.

&delta; Would like to see more about viewpoint in the lesson plan

&delta; Move Dev Tools demo earlier in the lesson

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
