### ISSUE TITLE
Placement of lessons

### ISSUE THREAD

**Issue by jacohen10** [ga-dc/curriculum#557]
Hey would it be possible to update the curriculum so all the lessons are in their weekly folders? For example, I noticed project3 and https://github.com/ga-dc/express-passport-local-authentication were not in the curriculum and I had a bit of trouble finding them at first. Would be really helpful for me especially when trying to review the material. 

Thanks!
Josh

**Comment by jshawl** [comment]
want to move the files yourself and submit a pull request?
