### ISSUE TITLE
gitbook fails attempting to parse `{{{body}}}`

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/curriculum#566]
Tracked gitbook error to the `{{{body}}}` within  "/Users/matt/dev/ga/wdi/curriculum/08-single-page-web-apps/git-teams/readme.md".  

```
Template render error: (/Users/matt/dev/ga/wdi/curriculum/08-single-page-web-apps/git-teams/readme.md) [Line 172, Column 52]
  parseAggregate: expected colon after dict key (In file '08-single-page-web-apps/git-teams/readme.md')
```

**Comment by jshawl** [comment]
https://github.com/GitbookIO/gitbook/blob/4fea85289e1d2cf41bd94656033b8b5748d80bd8/lib/template.js#L403

**Comment by mattscilipoti** [comment]
Found it.  The error is occurring inside [nunjucks (gitbook's tempting engine)](https://github.com/mozilla/nunjucks/blob/master/browser/nunjucks.js#L3056).  It is supposed to treat that area as raw markdown, but lines formatted as a list do not seem to be parsed correctly.

I have identified this with tests in gitbook_markdown repo.

```js
// test/page.js
it('should escape codeblocks in preparation (1)', function() {
  ...
      assert.equal(page.prepare("1. Hello `{{{handlebars_body}}}`"), "1. Hello {% raw %}`{{{handlebars_body}}}`{% endraw %}");
      assert.equal(page.prepare("- Hello `{{{handlebars_body}}}`"), "- Hello {% raw %}`{{{handlebars_body}}}`{% endraw %}");
    });
```

**Comment by mattscilipoti** [comment]
WORKAROUND: start the follow-up list items with dash.
