### ISSUE TITLE
ui router (matt)

### ISSUE THREAD

**Issue by jshawl** [ga-dc/curriculum#582]
∆: more explicit steps for getting starter code
∆: mention releases / tags in lesson plan
∆: recommend a you-do earlier. maybe john pappa styleguide hunt?

**Comment by jshawl** [comment]
why we need first parens in `(function(){})()`:

>... in `(...)()`, the first set of parenthese is merely a set of delimeters enclosing an expression.

**Comment by jshawl** [comment]
https://github.com/ga-dc/curriculum/commit/d477ea2b535a0e5b791a45c468082a24d9ef4dcd

**Comment by jshawl** [comment]
∆: disable cache while dev tools are open

**Comment by RobertAKARobin** [comment]
https://github.com/ga-dc/grumblr_angular/commit/d5023b54823d40476aa35cafa6aa5c9024458ed7

**Comment by jshawl** [comment]
∆: something out of order here - https://github.com/ga-dc/curriculum/tree/master/10-angular/ui_router#q-how-do-you-give-an-instance-of-a-javascript-object-a-property-from-inside-its-constructor-function console.log won't happen until called in a directive
