### ISSUE TITLE
Custom Directives (Adam)

### ISSUE THREAD

**Issue by amaseda** [ga-dc/curriculum#592]
∆ For the self-walkthrough exercise at the start of the resources class, we had them create a list of 3 things they wanted clarification on. We then talked about some of those things as a class. I think that would've made the intro exercise more helpful (although it was good as is!).

++ That high-level review and diagram at the end of class was AMAZING. Hope you screencasted this lesson so I can re-watch it.

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
