### ISSUE TITLE
Custom Directives (Jesse)

### ISSUE THREAD

**Issue by jmas13** [ga-dc/curriculum#593]
- (+) Great framing
  - (+) Rethinking best practices and web becoming modular
  - (+) What is your emotional response to this?
  - (+) Flagship of angular
- (+) Good balance of we-do and you-do
- (&Delta;) Typo in lesson plan fixed by Matt's [hotfix](https://github.com/ga-dc/curriculum/commit/8cb4271690094d1ddd4ce58c6e837d9ea4e7d00b)
- (&Delta;) Student noted that so many grumbl* variables is getting confusing

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
