### ISSUE TITLE
Auth(Adam)

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/curriculum#598]
`+` - I love the diff syntax, thought the `+` signs are irritating to copy/paste
`∆` - after the back end configuration, might be nice to open angular to show `http://localhost:3000/grumbles 401 (Unauthorized)`

**Comment by RobertAKARobin** [comment]
:heavy_plus_sign: I didn't know you could do that until today!

**Comment by andrewsunglaekim** [comment]
scratch that delta, you just covered it.. do it earlier? haha jk

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
