### ISSUE TITLE
Mapping (Adrian)

### ISSUE THREAD

**Issue by nolds9** [ga-dc/curriculum#613]
:heavy_plus_sign:'s:  
- Great intro, really liked how you turned it into a group discussion
- Loved all the You-Do's in this lesson, and liked how you engaged the class to share answers/provide solutions.

∆'s: 
- Update Instructions for `Mapbox Log In` section to factor in new Mapbox dashboard
- `Fun with Tiling` exercise could use some improved documentation/instructions. Some students were confused about how they related to the previous steps/ the tile we used originally.
- ∆/+ include link to/ blurb on [Geojson.io](http://geojson.io/) that was mentioned in class.

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
