### ISSUE TITLE
PHP/Wordpress (Jesse)

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/curriculum#616]
∆: Make sure to run through setting up XAMPP yourself!
+: Markham suggested to me a while ago:

> Hey - I came up with a better process for that idea I was toying with (regarding mid-class checkouts to help students keep in step). I think the instructor for the classroom could, instead of putting up static checkpoints before, simply push something like “active-classroom-5” before a break, and then students could checkout that version before class starts up again. Would likely be easier / more accurate for both parties.

...and today, at the end of the morning half:

```
​[12:24 PM] 
Markham Shofner what jesse just did was exactly what we talked about!
Markham Shofner (just right above) regarding using a live repo to help out the class to catchup to where he is
Markham Shofner it seemed really useful to catch folks up
```

**Comment by mattscilipoti** [comment]
Moved to ga-wdi-curriculum
