### ISSUE TITLE
content overlapping with nav bar, and fixing it.

### ISSUE THREAD

**Issue by onesick** [ga-dc/curriculum#618]
I tried to use float. But since it's CSS... Its giving me too hard time to fix it.
I tried to use float, but it's not working
I have made a fixed item on top, and it's overlapping with the contents

**Comment by onesick** [comment]
I tried to use float, but it's not working

**Comment by RobertAKARobin** [comment]
Please submit it here, Won: https://github.com/ga-dc/project4/issues
